covid_web/camera/urls.py
from django.urls import include, path
from rest_framework import routers
from . import views

# router = routers.DefaultRouter()
# router.register(r'cameras', views.CameraViewSet)
# router.register(r'images', views.ImageViewSet)

# app_name = 'camera'
# urlpatterns = [
#     path('', include(router.urls)),
#     path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
# ]

app_name = 'camera'
urlpatterns = [
    path('cameras/', views.CameraList.as_view()),
    path('images/', views.ImageList.as_view()),
    path('cameraForm/', views.CameraForm.as_view(), name='cameraForm'),
    path('cameraForm/response', views.cameraAdd, name='cameraAdd'),
    path('cameraForm/response/delete', views.cameraDel, name='cameraDel'),
    # path('api/image/add', views.ImageAPIadd.as_view(), name='imageAdd'),
]

covid_web/covid_web/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls')),
    path('camera/', include('camera.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

covid_web/login/urls.py
from django.urls import path

from . import views

app_name = 'login'
urlpatterns = [
    path('', views.LandingView.as_view(), name='landing'),
    path('aboutus/', views.AboutUsView.as_view(), name='aboutus'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('register/success/', views.register, name='register_success'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('auth/', views.auth, name='auth'),
    path('dashboard/', views.DashboardView.as_view(), name='dashboard'),
    path('account/', views.AccountView.as_view(), name='account'),
    path('account/acc_change', views.acc_change, name='acc_change'),
    path('logout/success/', views.LogoutView.as_view(), name='logout'),
    path('logout/', views.logout_control, name='logout_control'),
]

covid_web/camera/models.py
from email.policy import default
from django.db import models
from login.models import User

class Camera(models.Model):
    cameraName = models.CharField(max_length=50)
    ipAddress = models.GenericIPAddressField()
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    def __str__(self):
        return self.cameraName

class Image(models.Model):
    imageName = models.CharField(max_length=50)
    image = models.ImageField(upload_to='images/')
    temp = models.DecimalField(max_digits=5, decimal_places=1)
    camera = models.ForeignKey(Camera, on_delete=models.CASCADE)

covid_web/camera/views.py
import ipaddress
from .models import Camera, Image
from login.models import User
from .serializers import CameraSerializer, ImageSerializer
from rest_framework import generics, views
from django.shortcuts import redirect
from django.views.generic import TemplateView
from django.http import HttpResponse, request
from rest_framework.response import Response
from django.core.files.base import ContentFile
import base64

class CameraList(generics.ListCreateAPIView):
    queryset = Camera.objects.all()
    serializer_class = CameraSerializer


class ImageList(generics.ListCreateAPIView):
    queryset = Image.objects.all()
    serializer_class = ImageSerializer

    def post(self, request):
        try:
            imageName = request.POST['imageName'][len("uploads/"):]
            image64 = request.POST['image']
            ipAddress = request.POST['ipAddress']
            temp = request.POST['temp']
            camera = Camera.objects.get(ipAddress=ipAddress)
            
        except(Camera.DoesNotExist):
            print(request.META.get('REMOTE_ADDR'))
            return Response(data="Camera not registered to the system!", status=400)
        else:
            data = {
                'imageName':imageName, 
                'image':ContentFile(base64.b64decode(image64), name=imageName),
                'temp': temp,
                'camera':camera.id,
                }
            serializer = ImageSerializer(data=data)
            if serializer.is_valid():
                serializer.save()
                return Response(data=serializer.data, status=200)
            else:
                return Response(data=serializer.errors, status=400)

class CameraForm(TemplateView):
    template_name = "camera/cameraform.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = User.objects.get(username=self.request.session['username'])
        return context

def cameraAdd(request):
    try:
        username = request.session['username']
        user = User.objects.get(userName=username)

        cameraName = request.POST['cameraName']
        ipAddress = request.POST['ipAddress']
        oldCam = Camera.objects.get(cameraName=cameraName)
        oldCam = Camera.objects.get(ipAddress=ipAddress)

    except(Camera.DoesNotExist):
        newCamera = Camera(cameraName=cameraName, ipAddress=ipAddress, owner=user)
        newCamera.save()
        # should be success page
        return redirect('login:dashboard')

    else:
        response = "Camera IP already assigned.<a href=\"{% url 'login:dashboard' %}\"><button>Return to Dashboard</button></a>"
        return HttpResponse(response)

def cameraDel(request):
    try:
        username = request.session['username']
        user = User.objects.get(userName=username)

        camID = request.POST['id']
        cam = Camera.objects.get(id=camID)

    except(Camera.DoesNotExist):
        response = "Camera not found for deletion!<a href=\"{% url 'login:dashboard' %}\"><button>Return to Dashboard</button></a>"
        return HttpResponse(response)

    else:
        cam.delete()
        return redirect('login:dashboard')

covid_web/camera/templates/camera/cameraform.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>COVID Tracker: Camera Form</title>
    <link rel="stylesheet" href="style 2.css">
</head>
<body>
    <script>
        function validateForm(){
                var cameraName = document.registerForm.cameraName.value;
                var ipAddress = document.registerForm.ipAddress.value;
                
                if (cameraName==null || cameraName==""){
                    alert("Camera name can't be blank!");
                    return false;
                }
                else if(ipAddress==null || ipAddress==""){
                    alert("IP Address can't be blank!");
                    return false;
                }
            }
    </script>
    <div class="modal modal-signin position-static min-vh-100 d-flex flex-column justify-content-center py-5" tabindex="-1" role="dialog" id="modalSignin">
        <div class="modal-dialog">
          <div class="modal-content px-4 rounded-6 shadow">
            <div class="modal-header p-5 pb-4 border-bottom-0">
              <h2 class="fw-bold mb-0">Camera Form</h2>
            </div>
      
            <div class="modal-body p-5 pt-0">
              <form name="registerForm" method="post" onsubmit="return validateForm()" action="{% url 'camera:cameraAdd' %}"> {% csrf_token %}
                <div class="py-2">
                  <div class="form-floating mb-3">
                    <input name="cameraName" type="cameraName" class="form-control rounded-4" id="cameraName" placeholder="camera 1">
                    <label for="cameraName">Camera Name</label>
                  </div>
                  <div class="form-floating mb-3">
                    <input name="ipAddress" type="ipAddress" class="form-control rounded-4" id="ipAddress" placeholder="127.0.0.1">
                    <label for="ipAddress">IP Address</label>
                  </div>
                </div>
                
                <button class="w-100 mb-2 btn btn-lg rounded-4 btn-primary" type="submit">Add camera</button>
                <a href="{% url 'login:dashboard' %}"><button class="w-100 mb-2 btn btn-lg rounded-4 btn-secondary" type="button">Cancel</button></a>
              </form>
            </div>
          </div>
        </div>
      </div>
</body>
</html>