covid_web/camera/urls.py
from django.urls import include, path
from rest_framework import routers
from . import views

# router = routers.DefaultRouter()
# router.register(r'cameras', views.CameraViewSet)
# router.register(r'images', views.ImageViewSet)

# app_name = 'camera'
# urlpatterns = [
#     path('', include(router.urls)),
#     path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
# ]

app_name = 'camera'
urlpatterns = [
    path('cameras/', views.CameraList.as_view()),
    path('images/', views.ImageList.as_view()),
    path('cameraForm/', views.CameraForm.as_view(), name='cameraForm'),
    path('cameraForm/response', views.cameraAdd, name='cameraAdd'),
    path('cameraForm/response/delete', views.cameraDel, name='cameraDel'),
    # path('api/image/add', views.ImageAPIadd.as_view(), name='imageAdd'),
]

covid_web/covid_web/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls')),
    path('camera/', include('camera.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

covid_web/login/urls.py
from django.urls import path

from . import views

app_name = 'login'
urlpatterns = [
    path('', views.LandingView.as_view(), name='landing'),
    path('aboutus/', views.AboutUsView.as_view(), name='aboutus'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('register/success/', views.register, name='register_success'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('auth/', views.auth, name='auth'),
    path('dashboard/', views.DashboardView.as_view(), name='dashboard'),
    path('account/', views.AccountView.as_view(), name='account'),
    path('account/acc_change', views.acc_change, name='acc_change'),
    path('logout/success/', views.LogoutView.as_view(), name='logout'),
    path('logout/', views.logout_control, name='logout_control'),
]

covid_web/login/models.py
from django.db import models

class User(models.Model):
    userName = models.CharField(max_length=50)
    email = models.CharField(max_length=50)
    password = models.CharField(max_length=50)
    date = models.DateTimeField()
    allowed = models.BooleanField(default=False)
    def __str__(self):
        return self.userName

covid_web/login/views.py
from pyexpat import model
from urllib import request
from django.http import HttpResponse
from django.utils import timezone
from django.shortcuts import redirect
from django.views.generic import TemplateView, DetailView, ListView

from .models import User
from camera.models import Camera, Image

class LandingView(TemplateView):
    template_name = "login/landing.html"

class AboutUsView(TemplateView):
    template_name = "login/aboutus.html"

class RegisterView(TemplateView):
    template_name = "login/register.html"

def register(request):
    try:
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        oldUser = User.objects.get(userName=request.POST['username'])

    except(User.DoesNotExist):
        newUser = User(userName=username, email = email, password = password, date = timezone.now())
        newUser.save()
        # should be success page
        return redirect('login:login')

    else:
        response = "User existed."
        return HttpResponse(response)

class LoginView(TemplateView):
    template_name = 'login/login.html'

# login data to dashboard
def auth(request):
    try:
        username = request.POST['username']
        user = User.objects.get(userName=username)
    except (User.DoesNotExist):
        response = "User does not exists."
        return HttpResponse(response)
    else:
        if user.allowed == True:
            if user.password == request.POST['password']:
                request.session['username'] = username
                request.session['email'] = user.email
                return redirect('login:dashboard')
            else:
                response = "Password incorrect."
                return HttpResponse(response)
        else:
            response = "Registration not approved by admin. Please wait at least 1 day or contact the admin if urgent."
            return HttpResponse(response)

class DashboardView(ListView):
    model = Camera
    context_object_name = 'camera_list'
    template_name = 'login/dashboard.html'

    def get_context_data(self, **kwargs):
        context = super(DashboardView, self).get_context_data(**kwargs)
        context.update({
            'images_list': Image.objects.all(),
        })
        return context

    def get_queryset(self):
        user = User.objects.get(userName=self.request.session['username'])
        queryset = Camera.objects.all()
        queryset = queryset.filter(owner=user)
        return queryset

class AccountView(TemplateView):
    template_name = "login/account.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = User.objects.get(username=self.request.session['username'])
        return context

def acc_change(request):
    username = request.session['username']
    password = request.POST['password']
    user = User.objects.get(userName=username)
    user.password = password
    user.save()

    return redirect('login:dashboard')
    
class LogoutView(TemplateView):
    template_name = "login/logout.html"

def logout_control(request):
    request.session.flush()
    return redirect('login:landing')

covid_web/login/templates/login/aboutus.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {% load static %}
    <title>Landing Page</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'login/aboutus.css' %}"/>
    <link href="https://fonts.googleapis.com/css2?family=Maven+Pro:wght@400;500;600;700;800;900&display=swap" rel="stylesheet">
</head>
<body>
    <div id="landing-page">   
        <header id="header">
            <nav id="nav-bar">
                <a href="#"><img src="{% static 'login/images/logo.png' %}" id="header-img"></a>
                <div class="btn-group" role="group" aria-label="Basic example">
                    <a href="{% url 'login:landing' %}" class="btn btn-outline-primary">Home</a>
                    <a href="#" class="btn btn-outline-primary active">About Us</a>
                    <a href="{% url 'login:login' %}" class="btn btn-outline-primary">Login</a>
                </div>
            </nav>
        </header>
        <div class="content">
            <img id="cctv-image" src="{% static 'login/images/cctv.png' %}" alt="">
            <div id="text-aboutus">
                <h2>About Us</h2>
                <p>
                    In the current pandemic situation, 
                    all countries are fighting COVID-19 and are 
                    still looking for a practical and cost-effective 
                    solution to the problems that are arising in a variety of ways.
                    Researchers in physical sciences and engineering are attempting to meet 
                    such challenges by developing new theories, describing new research problems, 
                    developing user-centered explanations, and educating ourselves and the public.
                    The purpose of this brief review was to raise awareness of this innovative technology 
                    and its significant applications for the COVID-19 pandemic. That is when the IOT 
                    and real time processing comes handy to handle the situation. Real-time systems 
                    are now used in a wide range of applications, including avionics, automotive, 
                    and patient monitoring, to name a few. A Real-time System (RTS) is limited in 
                    its ability to carry out its functionality due to (strict) timing constraints. 
                    In this SDD the proposed system will provide a solution to detect probable COVID-19 
                    patients around using IOT in real time.
                </p>
            </div>
        </div>
    </div>
</body>
</html>

covid_web/login/templates/login/account.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'login/account.css' %}">
    <link rel="stylesheet"
        href="https://maxst.icons8.com/vue-static/landings/line-awesome/line-awesome/1.3.0/css/line-awesome.min.css">
    <title>COVID Tracker: Account</title>
</head>

<body>
    <div class="sidebar">
        <div class="sidebar-container">
            <div class="sidebar-logo">
                <img src="{% static 'login/images/logo.png' %}" alt="" id="#logo">
            </div>
            <div class="sidebar-avatar">
                <img src="{% static 'login/images/avatar.png' %}" alt="">
                <div class="sidebar-avatar-info">
                    <h4>{{ request.session.username }}</h4>
                </div>
            </div>
            <div class="sidebar-menu">
                <ul>
                    <li>
                        <a href="{% url 'login:dashboard' %}">
                            <span class="las la-video"></span>
                            <span class="sidebar-menu-text">Camera</span>
                        </a>
                    </li>
                    <li class="active">
                        <a href="#">
                            <span class="las la-cog"></span>
                            <span class="sidebar-menu-text">Settings</span>
                        </a>
                    </li>
                    <hr>
                    <li>
                        <a href="{% url 'login:logout_control' %}">
                            <span class="las la-sign-out-alt"></span>
                            <span class="sidebar-menu-text">Logout</span>
                        </a>
                    </li>
                    <li></li>
                </ul>
            </div>

        </div>

    </div>

    <div class="main-content">
        <header>
            <div class="content-title">
                <h4>Settings</h4>
                <p>| Manage your account settings.</p>
            </div>
            <div class="content">
                <h3>Hi, {{ request.session.username }}</h3>
                <div class="form-container">
                    <script>
                        function validateForm() {
                            var password = document.accountForm.password.value;
                            var confirm_password = document.accountForm.confirm_password.value;

                            if (password != confirm_password) {
                                alert("Password does not match!");
                                return false;
                            }
                        }
                    </script>
                    <form name="accountForm" method="post" class="form-password" onsubmit="return validateForm()" action="{% url 'login:acc_change' %}">{% csrf_token %}
                        <label for="e-mail">E-mail</label><br>
                        <input type="text" name="e-mail" value="{{ request.session.email }}" readonly
                            class="readonly"><br>
                        <label for="password">Change Password</label><br>
                        <input type="password" name="password" placeholder="Enter your new password" class="input-text"><br>
                        <label for="password">Confirm Password</label><br>
                        <input type="password" name="confirm_password" placeholder="Re-enter your new password"
                            class="input-text"><br>
                        <input type="submit" value="Submit" class="btn-submit">
                    </form>
                </div>
            </div>
        </header>
    </div>
</body>

</html>

covid_web/login/templates/login/dashboard.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'login/camera.css' %}">
    <link rel="stylesheet"
        href="https://maxst.icons8.com/vue-static/landings/line-awesome/line-awesome/1.3.0/css/line-awesome.min.css">
    <title>COVID Tracker: Dashboard</title>
</head>

<body>
    <div class="sidebar">
        <div class="sidebar-container">
            <div class="sidebar-logo">
                <img src="{% static 'login/images/logo.png' %}" alt="" id="#logo">
            </div>
            <div class="sidebar-avatar">
                <img src="{% static 'login/images/avatar.png' %}" alt="">
                <div class="sidebar-avatar-info">
                    <h4>{{ request.session.username }}</h4>
                </div>
            </div>
            <div class="sidebar-menu">
                <ul>
                    <li class="active">
                        <a href="#">
                            <span class="las la-video"></span>
                            <span class="sidebar-menu-text">Camera</span>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'login:account' %}">
                            <span class="las la-cog"></span>
                            <span class="sidebar-menu-text">Settings</span>
                        </a>
                    </li>
                    <hr>
                    <li>
                        <a href="{% url 'login:logout_control' %}">
                            <span class="las la-sign-out-alt"></span>
                            <span class="sidebar-menu-text">Logout</span>
                        </a>
                    </li>
                    <li></li>
                </ul>
            </div>

        </div>
    </div>

    <div class="main-content">
        <header>
            <div class="content-title">
                <h4>Camera</h4>
                <p>| Display live monitoring camera, to find COVID-19 suspects.</p>
            </div>
        </header>
        <div class="content">
            <h6>Supervisor: {{ request.session.username }}</h6>

            {% if camera_list %}
            {% block content %}
            {% for camera in camera_list %}
            <div class="accordion" id="accordion1">
                <div class="accordion-item">
                    <h2 class="accordion-header" id="head{{ camera.id }}">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                            data-bs-target="#collapse{{ camera.id }}" aria-expanded="true"
                            aria-controls="collapse{{ camera.id }}">
                            {{ camera.cameraName }}
                        </button>
                    </h2>
                    <div id="collapse{{ camera.id }}" class="accordion-collapse collapse"
                        aria-labelledby="head{{ camera.id }}" data-bs-parent="#accordion1">
                        <div class="accordion-body">
                            <div class="row">
                                {% for image in images_list %}
                                {% if image.camera == camera %}
                                <div class="col">
                                    <img src="../media/{{ image.image }}" class="img-thumbnail" alt="img">
                                    <div>{{image.temp}} C</div>
                                    <div class="col-3 mx-auto">
                                        <a href="#" onclick="return alert('Not implemented!')"><button type="button"
                                                class="btn btn-warning">Report</button></a>
                                    </div>
                                </div>
                                {% endif %}
                                {% endfor %}
                            </div>
                            <br>
                            <form action="{% url 'camera:cameraDel' %}" method="post"
                                onsubmit="return confirm('Are you sure you want to delete {{ camera.cameraName }}?');">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="d-grid col-4 mx-auto">
                                        <button class="btn btn-danger" type="submit" name="id"
                                            value="{{ camera.id }}">Delete
                                            Camera</button>
                                    </div>
                                </div>
                            </form>

                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
            {% endblock %}
            {% else %}
            <div class="content-container">
                <div class="card-container">
                    <div class="camera-card">
                        <div class="card-info">
                            <p>No Cam Detected</p>
                        </div>
                        <a href="{% url 'camera:cameraForm' %}"><button>Add Camera</button></a>
                    </div>
                </div>
            </div>
            {% endif %}
            <br>
            <div class="row">
                <div class="d-grid col-4 mx-auto">
                    <a href="{% url 'camera:cameraForm' %}" class="btn btn-success">Add Camera</a>
                </div>
            </div>
        </div>

    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
    <script type="text/javascript">
        $(document).on('click', '.sidebar-menu ul li', function () {
            $(this).addClass('active').siblings().removeClass('active')
        })
    </script>
</body>

</html>

covid_web/login/templates/login/landing.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {% load static %}
    <title>Landing Page</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'login/landing.css' %}" />
</head>

<body>
    <div id="landing-page">
        <header id="header">
            <nav id="nav-bar">
                <a href="#"><img src="{% static 'login/images/logo.png' %}" id="header-img"></a>
                <div class="btn-group" role="group" aria-label="Basic example">
                    <a href="#" class="btn btn-outline-primary active">Home</a>
                    <a href="{% url 'login:aboutus' %}" class="btn btn-outline-primary">About Us</a>
                    <a href="{% url 'login:login' %}" class="btn btn-outline-primary">Login</a>
                </div>
            </nav>
        </header>
        <div class="content">
            <div class="col-40">
                <h2>Let's Break<br><span id="highlight-text">The COVID-19 Chain</span> Together</h2>
            </div>
            <div class="col-60">
                <img id="bg-image" src="{% static 'login/images/bg.png' %}" alt="">
            </div>
        </div>
    </div>
</body>

</html>

covid_web/login/templates/login/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'login/styles.css' %}">

    <title>COVID Tracker: Login</title>
</head>
<body>
    <script>
        function validateForm(){
                var username = document.loginForm.username.value;
                var password = document.loginForm.password.value;
                
                if (username==null || username==""){
                    alert("Name can't be blank!");
                    return false;
                }
                else if(password==null || password==""){
                    alert("Password can't be blank!");
                    return false;
                }
            }
    </script>
    <div class="modal modal-signin position-static min-vh-100 d-flex flex-column justify-content-center py-5" tabindex="-1" role="dialog" id="modalSignin">
        <div class="modal-dialog">
          <div class="modal-content px-4 rounded-6 shadow">
            <div class="modal-header p-5 pb-4 border-bottom-0">
              <h2 class="fw-bold mb-0">Login</h2>
            </div>
      
            <div class="modal-body p-5 pt-0">
              <form name="loginForm" method="post" onsubmit="return validateForm()" action="{% url 'login:auth' %}">{% csrf_token %}
                <div class="py-2">
                  <div class="form-floating mb-3">
                    <input name="username" type="username" class="form-control rounded-4" id="floatingInput" placeholder="example">
                    <label for="floatingInput">Username</label>
                  </div>
                  <div class="form-floating mb-3">
                    <input name="password" type="password" class="form-control rounded-4" id="floatingPassword" placeholder="password">
                    <label for="floatingPassword">Password</label>
                  </div>
                </div>
                
                <button class="w-100 mb-2 btn btn-lg rounded-4 btn-primary" type="submit">Login</button>
                <p>Not a user? <a href="{% url 'login:register' %}">Register here!</a></p>
              </form>
            </div>
          </div>
        </div>
      </div>
</body>
</html>

covid_web/login/templates/login/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'login/styles.css' %}">

    <title>COVID Tracker: Login</title>
</head>
<body>
    <div class="modal modal-signin position-static min-vh-100 d-flex flex-column justify-content-center py-5" tabindex="-1" role="dialog" id="modalSignin">
        <div class="modal-dialog">
          <div class="modal-content px-4 rounded-6 shadow">
            <div class="modal-header p-5">
              <a href="{% url 'login:landing' %}" style="text-decoration: none; color: black;"><h2 class="fw-bold mb-0">Successfully logout!</h2></a>
            </div>
          </div>
        </div>
    </div>
</body>
</html>

covid_web/login/templates/login/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'login/styles.css' %}">

    <title>COVID Tracker: Sign Up</title>
    <link rel="stylesheet" href="style 2.css">
</head>
<body>
    <script>
        function validateForm(){
                var username = document.loginForm.username.value;
                var password = document.loginForm.password.value;
                
                if (username==null || username==""){
                    alert("Name can't be blank!");
                    return false;
                }
                else if(email==null || password==""){
                    alert("Email can't be blank!");
                    return false;
                }
                if (password==null || password==""){
                    alert("Password can't be blank!");
                    return false;
                }
                else if(password==confirmpassword){
                    alert("Confirm password is not the same!");
                    return false;
                }
            }
    </script>
    <div class="modal modal-signin position-static min-vh-100 d-flex flex-column justify-content-center py-5" tabindex="-1" role="dialog" id="modalSignin">
        <div class="modal-dialog">
          <div class="modal-content px-4 rounded-6 shadow">
            <div class="modal-header p-5 pb-4 border-bottom-0">
              <h2 class="fw-bold mb-0">Sign Up</h2>
            </div>
      
            <div class="modal-body p-5 pt-0">
              <form name="registerForm" method="post" onsubmit="return validateForm()" action="{% url 'login:register_success' %}"> {% csrf_token %}
                <div class="py-2">
                  <div class="form-floating mb-3">
                    <input name="username" type="username" class="form-control rounded-4" id="username" placeholder="username">
                    <label for="username">Username</label>
                  </div>
                  <div class="form-floating mb-3">
                    <input name="email" type="email" class="form-control rounded-4" id="email" placeholder="name@example.com">
                    <label for="email">Email</label>
                  </div>
                  <div class="form-floating mb-3">
                    <input name="password" type="password" class="form-control rounded-4" id="password" placeholder="Password">
                    <label for="password">Password</label>
                  </div>
                  <div class="form-floating mb-3">
                    <input name="confirmpassword" type="password" class="form-control rounded-4" id="confirmpassword" placeholder="Password">
                    <label for="confirmpassword">Confirm Password</label>
                  </div>
                </div>
                
                <button class="w-100 mb-2 btn btn-lg rounded-4 btn-primary" type="submit">Sign up</button>
                <p>Already have an account? <a href="{% url 'login:login' %}">Login</a></p>
              </form>
            </div>
          </div>
        </div>
      </div>
</body>
</html>